version: "3.9"

services:
  wiremock:
    container_name: "wiremock"
    image: "wiremock/wiremock:2.32.0"
    ports:
      - "8081:8080"
    volumes:
      - "./wiremock/example-api:/home/wiremock"

  grafana-loki:
    container_name: "loki"
    image: "grafana/loki:latest"
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"

  promtail:
    image: "grafana/promtail:latest"
    volumes:
      - /var/log:/var/log
    command: -config.file=/etc/promtail/config.yml

  grafana:
    container_name: "grafana"
    image: "grafana/grafana:latest"
    ports:
      - "3000:3000"
    depends_on:
      - grafana-loki
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy 
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
